### ISSUE TITLE
The Javadoc class comments are overly complicated.

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#108]
Maybe a brief description of what the class represents is useful, but the rest seems unnecessary.

* They actually clutter and lengthen the file making it harder to mentally process, not easier.
* There is no point knowing the (original) author of a class. This can be found out from version control but it's also irrelevant once enough changes have happened.
* Can anyone explain the usefulness of the @version and @since things?

I propose getting rid of them altogether or just requiring the brief description mentioned above.
(Qulice cannot guarantee that the comments are actually good so review is still required.)

**Comment by alex-semenyuk** [comment]
About the usefulness of the @version, @since and @author refer to http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#
Of course, all of them can be to get rid of, as well as the whole class comment, but you try to go against rules/conventions mentioned above, the worst thing that you didn't suggest another strict rule and it can bring chaos to the project.
The idea that needs to review - it's true, but unfortunately in practice I never seen a review, in which somebody write something like: "you write incomprehensible comment", attention of review it's code

**Comment by pa9ey** [comment]
@alex-semenyuk 
>About the usefulness of the @version, @since and @author refer to...

1. Nothing jumps out at me in that link regarding usefulness. (Did you have anything particular in mind?)
2. I hope you realise that by "usefulness" I mean *useful to us, right here, right now, on this project, in this context*.

>Of course, all of them can be to get rid of, as well as the whole class comment...

Of course.

>but you try to go against rules/conventions mentioned above...

No I don't. "This document describes *the style guide, tag and image conventions* we use in documentation comments for Java programs written *at Java Software, Oracle*." [Emphasis mine.]

>I never seen a review, in which somebody write something like: "you write incomprehensible comment"...

Maybe that's because you've never worked with me. :)

Nothing in your comment seems to address my objections. And there is a continuing (and strange) idea that somehow Qulice improves on what is possible with a mere review. That's ridiculous. Qulice doesn't even guarantee the *presence* of a comment. (Let alone a decent or useful one.) All it guarantees is the presence of *a comment block*.

**Comment by yegor256** [comment]
@pa9ey this is a good concern you raised, but it has to be submitted to qulice repository: https://github.com/teamed/qulice We just use Qulice and have no ability to change any of that rules.

**Comment by pa9ey** [comment]
@yegor256 Ah. Okay. I was assuming it was configurable in some way.
