### ISSUE TITLE
Why are we drowning every file in the noise of the MIT license?

### ISSUE THREAD

**Issue by pa9ey** [yegor256/eo#119]
I'm probably going to get some stick for this (https://github.com/yegor256/eo/pull/118#issuecomment-277089539) so I thought I'd at least make it an official issue and see what people think, rather than just leaving it as a snarky comment. (Sorry @g4s8!)

@stain already added a license file (https://github.com/yegor256/eo/blob/master/LICENSE) and a section in the README (https://github.com/yegor256/eo#license) so why must we replicate this in every single file? (At the very least, couldn't we just link to the license file?)

As it stands, it's just ugly distraction and noise.

**Comment by g4s8** [comment]
@pa9ey Agree, license header in each source file is over the odds. I'd prefer to include the link to license instead of full text:
```java
/*
 * License: https://github.com/yegor256/eo/blob/master/LICENSE
 */
package org.eolang.compiler.syntax;
```

**Comment by pa9ey** [comment]
So what do people think of this? Any objections?

Looked quickly at GitHub themselves and at Microsoft (random choices) to see what they do.

Microsoft have a short header with the copyright message and a note to tell you to go look at the general license file.

GitHub have no header at all in their files, just a license file at the top level of the project.

**Comment by pa9ey** [comment]
"As a best practice, we encourage you to include the license file with your project [in the root of the repository]."
https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license

There is no mention of putting in every file. Not even a reference to it.

**Comment by pa9ey** [comment]
Oh never mind.  It's enforced by Qulice again.
(Qulice seriously needs a "low noise" setting...)

I think I'm probably in danger of getting kicked out of the Qulice club:
https://github.com/teamed/qulice/issues/326#issuecomment-58991903
;^)

**Comment by pa9ey** [comment]
![image](https://cloud.githubusercontent.com/assets/18754996/22866937/e5e71cc6-f175-11e6-8ad0-69483637ce5c.png)

**Comment by pa9ey** [comment]
😉

**Comment by stain** [comment]
On Sat, 04 Feb 2017 08:45:07 -0800, John Page <notifications@github.com> wrote:
> Oh never mind.  It's enforced by Qulice again.
> (Qulice seriously needs a "low noise" setting...)
> 
> I think I'm probably in danger of getting kicked out of the Qulice club:
> https://github.com/teamed/qulice/issues/326#issuecomment-58991903
> ;^)

Technically the single LICENSE file should be enough - given that this
covers ALL the files.

At the Apache Software Foundation we always require license header in
each source file as well, so that it's origin and license can be
tracked. This becomes important when the project is long-lived, might
change ownership or starts mixing files from different sources, and also
makes it easier for others to re-use individual files separately.

Given that we're making a new language, which.. if we are very lucky,
gets popular - then I would rather have the license headers in early,
because I can tell you from experience it is a pain to go through 10
years of commit logs later to clear up where things came from.

-- 
Stian Soiland-Reyes
University of Manchester
http://www.esciencelab.org.uk/
http://orcid.org/0000-0001-9842-9718

**Comment by pa9ey** [comment]
**I'm thinking it's very unlikely we'd be able to convince the Qulice folks to change this stuff so barring any objections I'm going to close this issue.**

For the record, I think I'm convinced that per-file license information is a good idea. Or at least a unfortunate necessity. But personally I would make it as small as possible and not actually include the text of the license.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/eo#119` was not in scope

**Comment by pa9ey** [comment]
@yegor256 What's @0crat on about? :)
