### ISSUE TITLE
why do we need primary constructors

### ISSUE THREAD

**Issue by yegor256** [yegor256/eo#61]
I think that in <del>most</del> all cases primary constructors will just save arguments into attributes. So, the question is, why do we need to declare them? I'm suggesting to prohibit them and use only secondary ones.

**Comment by aravindps** [comment]
@yegor256 It is okay, if the main constructor is used only for setting values to all the attributes. What happens for derived attributes or constants in the object?

```javascript
Player player = Player.new("a"){
	String .name
	int .overallScore
	new(String name) {
	    .name = name
	    .overallScore = 0
	}
}
```

If the constructor allows has named arguments, it makes sense.

```javascript
Player player = Player.new(name="a"){
	String .name
	int .overallScore
	new(String name) {
	    .name = name
	    .overallScore = 0
	}
}
```

**Comment by mdbs99** [comment]
@yegor256 always will exists a primary constructor, even if you don't create one.
I mean, all constructor we create will be a second.
So I think we can forget this ticket.

**Comment by NikoGJ** [comment]
In some old programming languages, programs were made of 2 distincts parts, the declaration part with the initialization of variables and the actual code which is using them.

I wonder if this "usage" could be applied to OO....
Can we imagine an object having 2 modes, an initialization mode which would be just basic linking object attributes and setup, and a runtime mode (the actual simulation mode made of method calls between objects, the one that we're used to). 2 opaque and isolated worlds.

It's just an idea though, I'm saying this because what we do when creating objects and initialize their state require a different set of methods than when we use them..

**Comment by yegor256** [comment]
@aravindps in this case we just create a primary ctor, which accepts _all_ arguments and then a secondary one, which provides defaults:

```
Player player = Player.new("a"){
	String .name
	int .overallScore
	new(String name) {
	    new(name, 0)
	}
	new(String name, int score) {
	    .name = name
	    .overallScore = score
	}
}
```

**Comment by g4s8** [comment]
I  think that we need primary constructor declaration (without any code or attribute initialization) to specify parameters order. Without it attributes initialization may be ambiguous. E.g. object from Readme:
```
object alphabet as Book:
  Text @isbn
  Text @title
  ctor()
    alphabet:
      "978-1-51916-691-3",
      "The Alphabet"
  ctor(String i, String t):
    @isbn = i
    @title = t
  Text asText():
    sprintf:
      "ISBN is %s, title is '%s'",
      @isbn,
      @title
```
It's not clear (without primary constructor) where is `title` and where is `isbn`, because both paraeters are strings:
```
ctor()
    alphabet:
      "978-1-51916-691-3",
      "The Alphabet"
```

So I suggest to declare primary constructor like this:
```
ctor(String isbn, String title)
```
 * without body
 * without colon
 * parameter names are same as attribute names

@yegor256 , what do you say?

**Comment by yegor256** [comment]
@g4s8 but the order of parameters we can infer from the order of object attributes. In this example:

```
object alphabet as Book:
  Text @isbn
  Text @title
  ctor()
    alphabet:
      "978-1-51916-691-3",
      "The Alphabet"
  ctor(String i, String t):
    @isbn = i
    @title = t
```

We know that `@isbn` goes first and `@title` goes next. What is the point of repeating this fact again in a constructor?

**Comment by g4s8** [comment]
> We know that `@isbn` goes first and `@title` goes next. What is the point of repeating this fact again in a constructor?

Looks logical, in this way we don't need primary constructors at all.

**Comment by yegor256** [comment]
@g4s8 I think it's important to update README too, after #112

**Comment by g4s8** [comment]
@yegor256 done!

**Comment by yegor256** [comment]
@g4s8 thanks a lot!
